### ISSUE TITLE
Can't Enable The plugin 

### ISSUE THREAD

**Issue by SGF-Git** [a1studmuffin/SpaceshipGenerator#10]
![plugin not working](https://cloud.githubusercontent.com/assets/19214796/16291444/e11434c2-38bb-11e6-9332-c314c38b8fc1.png)
That is the error message it gave me.

**Comment by a1studmuffin** [comment]
Did you download the correct ZIP from the releases page? Latest is: https://github.com/a1studmuffin/SpaceshipGenerator/releases/download/v0.1.1/add_mesh_SpaceshipGenerator.zip

**Comment by SGF-Git** [comment]
Ok so it's working not sure if i should make a basic ship shape or just let it go seems like i should just let it make something considering it's not using and ship like shapes i make.
