### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by willtheorangeguy** [a1studmuffin/SpaceshipGenerator#11]
I try to add the folder to the add-on's section but it won't let me? 
Any help?

**Comment by a1studmuffin** [comment]
Did you download the correct ZIP file from the releases page? Latest is: https://github.com/a1studmuffin/SpaceshipGenerator/releases/download/v0.1.1/add_mesh_SpaceshipGenerator.zip

**Comment by willtheorangeguy** [comment]
Okay. I'll try again. 
Do you have to extract the ZIP file first or do you leave it as a ZIP file?

**Comment by a1studmuffin** [comment]
Just leave it as the ZIP file and point Blender to it.

**Comment by willtheorangeguy** [comment]
OK
