### ISSUE TITLE
import fails when activating addon using Blender 2.77

### ISSUE THREAD

**Issue by AtomicPerception** [a1studmuffin/SpaceshipGenerator#12]
There is an error on line #18 of __init__.py.
`from add_mesh_SpaceshipGenerator import spaceship_generator`
This needs to be changed to 
`from . import spaceship_generator`

**Comment by a1studmuffin** [comment]
Was this using the correct release zip? Or the master repository zip?

**Comment by AtomicPerception** [comment]
I just downloaded the master ZIP.

**Comment by a1studmuffin** [comment]
Fixed, thanks for the solution.

**Comment by AtomicPerception** [comment]
Cool, did you have a chance to look at my fork?

I took your generation code and embedded into my parametric object framework. 

This allows you to bind the generation properties to a custom property on a a mesh based object. The net effect is that you can select the object and change the parameters at any time, even animate the parameters if you like (morphable spaceships...). Because it is bound to the object you can have as many as you like in the scene and edit them at any time or in any order.

**Comment by a1studmuffin** [comment]
Nice one! You obviously know a bit more about Blender than me - when I wrote the generator originally I just did a quick skim on Google for the easiest + cheapest way to manipulate 3D meshes/materials with Python, Blender won. I'm continually impressed with the stuff people are doing beyond the original script!
