### ISSUE TITLE
Forked your repository

### ISSUE THREAD

**Issue by pamrulla** [a1studmuffin/SpaceshipGenerator#13]
Hi,

I did not find any way to contact you via github, so I am contacting you via issues, I am extremely sorry for this. I saw your script for space ship generation and impressed by it, also I forked it and plan to improve it in multiple ways like sphere share space ship, pyramid, pentagon etc. Also planned to make it low polygon for games etc. Currently I have added create button, presets, y - z directions also and reset button. You can find link for it at blenderartists is [https://blenderartists.org/forum/showthread.php?401861-Space-Ship-Generator-Addon]

As I am pretty new to blender python and 3d programming, you are a professional. Is it ok with you if I update and when I feel it working fine with my changes, I can ask you for incorporate my changes. I am making it as open ofcourse.

Looking forward to hear from you.

**Comment by andyrst** [comment]
Hi

It's not my repository. Im just watcher of original repo. Original repo is
there:

https://github.com/a1studmuffin/SpaceshipGenerator

**Comment by a1studmuffin** [comment]
Hey pamrulla, great to hear from you! Sounds very cool, if you've got bugfixes or small improvements on the original script, definitely send me a pull request and I'll merge them into the master branch. If you're planning on making larger changes (eg. adding new types of spaceships) or evolving the project over a long period of time, it might be best to keep it as a separate project as I wasn't planning on doing further work beyond minor bugfixes/improvements. That said, I'm happy to point people to your branch if you're actively working on it further. You can reach me at michael@spaceduststudios.com.
