### ISSUE TITLE
Typos when calling 'generate_spaceship'

### ISSUE THREAD

**Issue by codeagent** [a1studmuffin/SpaceshipGenerator#15]
Hi @a1studmuffin, nice plugin, but i have found some typos in your code.
In __init__.py file the function call should be: 
```
spaceship_generator.generate_spaceship(
  self.random_seed,
  self.num_hull_segments_min,
  self.num_hull_segments_max,
  self.create_asymmetry_segments,
  self.num_asymmetry_segments_min,
  self.num_asymmetry_segments_max,
  self.create_face_detail,
  self.allow_horizontal_symmetry,
  self.allow_vertical_symmetry,
  self.apply_bevel_modifier,
  self.assign_materials
)
```

Now arguments num_hull_segments_min and num_hull_segments_max are not passed, and assign_materials also.

**Comment by a1studmuffin** [comment]
Ah nice one, thank you. I'll fix this up shortly.

**Comment by a1studmuffin** [comment]
Cheers, fixed in https://github.com/a1studmuffin/SpaceshipGenerator/commit/661f54c507edefcad6a624543896c3d1c1d882db
