### ISSUE TITLE
Generating large amounts of spaceships

### ISSUE THREAD

**Issue by superslow** [a1studmuffin/SpaceshipGenerator#18]
I don't really know if this is an issue as such, but I hope it is ok here.

I would like to generate a large amount of ships, add a decimate modifier(to reduce polys) and save them all as .fbx files. I have looked at the code but I am a really bad at python and am unsure as how to bulk save like this. How would I go about this? Thanks.

**Comment by a1studmuffin** [comment]
Sounds possible, but I don't have the answer on-hand so you'd need to learn Python to attempt this yourself. It's really not as scary as it seems, Python is useful for a million other things outside of this script... one of us... one of us: https://docs.python.org/2/tutorial/index.html
