### ISSUE TITLE
No lights when ship is created

### ISSUE THREAD

**Issue by MazenS** [a1studmuffin/SpaceshipGenerator#2]
Hello awesome tool, one wee problem - I'm not seeing any lights when I use the tool.
Any idea what I'm doing wrong?
![ship](https://cloud.githubusercontent.com/assets/11826437/16169108/dc3e50fe-3519-11e6-8db3-0f774027247d.jpg)

**Comment by a1studmuffin** [comment]
Try switching the viewport shading to Texture, Material or Rendered: 
https://www.blender.org/manual/editors/3dview/display/shading.html

If that still doesn't work, check you've put the texture PNGs in the right place relative to the script (same as the layout in the GitHub repo).

Cheers!

**Comment by MazenS** [comment]
That was it - Blender newbie. Cheers!
