### ISSUE TITLE
Stupidy McStupidQuestion: How do I render ships?

### ISSUE THREAD

**Issue by SupernovaCo** [a1studmuffin/SpaceshipGenerator#20]
Am I an idiot, or how do I get a generated ship to render like the pictures in the Readme? I run the default render settings, and the ships just look kind of flat, and the hull panels texture is almost invisible.

**Comment by SupernovaCo** [comment]
Oh, also another question: How do I get it to render like you did? I run the default render settings, and the ships just look kind of flat, and the hull panels texture is almost invisible.

**Comment by a1studmuffin** [comment]
A fellow idiot - high five! :) I think we resolved this over email so closing the issue, cheers.

**Comment by SupernovaCo** [comment]
Email..? I seriously do  not recall getting any emails from you

**Comment by a1studmuffin** [comment]
Maybe it was YouTube comments? If it wasn't you it was just a massive coincidence that someone else was asking the same thing. :) I had to create a mirror plane in a separate scene to render those images. To get the detail on the hull I believe I rendered at a higher resolution and scaled down later in an external program.

**Comment by SupernovaCo** [comment]
Huh. I was in the YouTube comments.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

*--Marvin_Megavolt*
