### ISSUE TITLE
how do start?

### ISSUE THREAD

**Issue by BJMShaw** [a1studmuffin/SpaceshipGenerator#21]
it's not working 4 me or u have made the how-to-start without it say the exact way of doing it.

**Comment by Vinc3r** [comment]
Agreed, a little explicit *how-to* may be appreciated :)

**Comment by MajickTek** [comment]
How to generate a spaceship:

Shift-A in object mode:

Clcik spaceship

If you mean how to install it, he gives instructions on how to do that.

**Comment by MajickTek** [comment]
Keep in mind that the textures only seem to work in Bender Render, and only show up properly when you're rendering.
