### ISSUE TITLE
[Documentation] How to add your own textures?

### ISSUE THREAD

**Issue by shevegen** [a1studmuffin/SpaceshipGenerator#22]
Hello Michael,

Not sure if this is worth reporting or not; please do feel free to close this issue at any moment in time.

Could a short subsection be added to explain how to add your own textures? I see that there are three .png files with the source code, so I assume that any .png file may work fine; but I have not tried so yet, so I'd like a pointer or two ideally in the documentation if that is possible. (I intend to test it lateron; blender's interface is pretty complex and I am no expert in python so it is not that trivial for me. Thanks!)

**Comment by a1studmuffin** [comment]
Thanks for the suggestion, I'll add a section to the documentation now explaining what the textures are used for. You're right in that you can just swap them out for your own ones.
