### ISSUE TITLE
Differently sized spaceships, including smaller ones?

### ISSUE THREAD

**Issue by ghost** [a1studmuffin/SpaceshipGenerator#23]
Hello Michael,

Not sure if this issue request is useful; if not, or if time is in short supply, please do feel free to close it down.

The spaceship generator idea is pretty cool; the spaceships are quite awesome too, some are just ... alien-weird. Would be cool to create meshes including inner structures e. g. such that one could use that for 3D games as-is. :D But this is not the feature suggestion here, just a random idea.

Feature request:

- Would it be possible to also include examples (and screenshots) of smaller spaceships? The ones that seem to be generated by default seem to be fairly large ones. The idea may be to generate a wider range of spaceships, including smaller protective-ships accompanying the larger ones - a bit like in master of orion if anyone remembers that old game.

Anyway, if this is too much work, please ignore. The generated spaceships as-is are pretty cool.

Hope you have similar great ideas in the future. \o/

**Comment by a1studmuffin** [comment]
Thanks for the suggestions! To be honest I'm happy to leave it where it's at and let people play with it instead, but appreciate the thought. I'd love to do interiors as well but that's a big job... maybe for another procedural generation challenge eh? :)
