### ISSUE TITLE
Examples of parameters for generate_spaceship function

### ISSUE THREAD

**Issue by mixedbredie** [a1studmuffin/SpaceshipGenerator#24]
Not and issue as such but could you provide a few examples of the different parameters you can pass to the `generate_spaceship` function?

What, for example, did you pass through to make the extreme ships?

**Comment by johnstt** [comment]
I'm also really interested in the exact same question!

**Comment by a1studmuffin** [comment]
From memory I think those extreme ships were made with the number of hull segments and asymmetry segments both set to around 20, but you'd have to give it a test run to verify for yourself. Essentially the higher those two numbers are, the longer and pointier the spaceships will be compared to the "normal" reference examples. So just think of those numbers as a sliding scale to control the growth of the spaceship's hull length, and asymmetrical growths off random faces. As mentioned in the readme, the best thing to do is play around with them to get a feel for how it works.
