### ISSUE TITLE
Run in Blender 2.8

### ISSUE THREAD

**Issue by vincent** [a1studmuffin/SpaceshipGenerator#27]
Hi, thank you for the script !

Blender 2.8 changed some core functions.
It is certainly too soon to adapt the script now, as some changes are not completely settled, nor documented, yet (stable release in forseen in 2019 Q3 I think)

Anyway, I did some minor changes to run it in Blender 2.8, without materials.
https://github.com/vincent/SpaceshipGenerator

The code is absolutely not polished - hence no pr yet - but can be useful if you just want to try it in 2.8.

Cheers

**Comment by xan2622** [comment]
@a1studmuffin Hi. do you plan to update your script for Blender 2.8?
Many scripts are now compatible: https://github.com/a1studmuffin/SpaceshipGenerator

**Comment by a1studmuffin** [comment]
Sorry for the incredibly long delay responding! :) 2.8 support would be cool but I don't have a lot of time at the moment to look into it. There's a couple of other bugs I've noticed with the texturing in the more recent versions of Blender. So perhaps at some point I'll scrub it up but can't say when that will be, sorry.
