### ISSUE TITLE
Add mesh spaceship not available

### ISSUE THREAD

**Issue by troynatural** [a1studmuffin/SpaceshipGenerator#28]
Add mesh spaceship not available in add menu (shift+A). After succesfully installing this addon in Blender 2.8, it's not available in add menu.

**Comment by Jakeukalane** [comment]
Also happens to me, the script itself says that it need update for compatibility for Blender 2.8

**Comment by Jakeukalane** [comment]
Did this: https://github.com/Jakeukalane/jakeukalane.github.io/blob/master/add_mesh_SpaceshipGenerator-2.80.zip

following this: https://github.com/vincent/SpaceshipGenerator/commit/52e7649883713040c27a0f399b494b352821d908#diff-743b1adbf37db12e16e01ef62a6f7d72

**Comment by XaeroDegreaz** [comment]
@Jakeukalane Weird -- it still does not show up in the addons menu in order to enable it for me on 2.80

**Comment by RegulusFen** [comment]
No selection in Add>Mesh after enabling addon in preferences in 2.80/2.81.

Oddly the plugin works as intended in 2.79.

does anyone have a fix for 2.8x?

**Comment by ldo** [comment]
Try my [version for 2.8](https://github.com/ldo/blender_spaceship_generator).

**Comment by ben-carson** [comment]
> Try my [version for 2.8](https://github.com/ldo/blender_spaceship_generator).

Confirmed working on OS X for v2.82 including textures. @ldo has done a great job carrying this project forward. I'd recommend using their repo going forward.

**Comment by kingdunadd** [comment]
> Try my [version for 2.8](https://github.com/ldo/blender_spaceship_generator).

@ldo 's version also works on Manjaro Linux with Blender 2.8.
