### ISSUE TITLE
States an upgrade to 2.8x is required

### ISSUE THREAD

**Issue by FeralKatt** [a1studmuffin/SpaceshipGenerator#31]
would love to try it

**Comment by Oxervision** [comment]
I modified the init.py file and the addon is showed in the Menu > Add > Mesh now but if you change some parameters it appears error message.

![error message](https://user-images.githubusercontent.com/46649474/72401344-00e0dc00-374c-11ea-952e-6591ab64aba9.jpg)

**Comment by nateisgood** [comment]
I'm having the same problem. Do you mind explaining how you changed the `__init__.py`?

**Comment by Oxervision** [comment]
This is the init.py file modified

[__init__.zip](https://github.com/a1studmuffin/SpaceshipGenerator/files/4106719/__init__.zip)

I found this information about the issue but I don't know how to fix it: https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API

**Comment by xzkeee** [comment]
Change your init file and show up the add spaceship option.
But when I try to add this also show up the same traceback error message.

**Comment by Oxervision** [comment]
Perhaps someone with knowlements in the new 2.8 API can help us.

**Comment by andytriboletti** [comment]
I also would like to try it, but I get the same error.

**Comment by andytriboletti** [comment]
Here's a fork that works with 2.8: https://github.com/BlenderCN/add_mesh_SpaceshipGenerator

**Comment by andytriboletti** [comment]
Result: 
![ship](https://user-images.githubusercontent.com/78852/74845233-b0394180-52fc-11ea-87cf-54c3c85b2380.png)

I got it working by using Cheetah3d on mac to apply the texture. Here's the result. Who wants to make a SceneKit/SceneForm space game? :)

**Comment by ldo** [comment]
I have done a 2.8-compatible version, including full generation of materials, [here](https://github.com/ldo/blender_spaceship_generator).

**Comment by Oxervision** [comment]
Thanks!!  
Tested on Blender 2.83.13 macOS and it works fine.

**Comment by LendoK** [comment]
An other 2.8 port is [here](https://github.com/LendoK/SpaceshipGenerator/tree/port_to_280)
