### ISSUE TITLE
Install instructions out of date?

### ISSUE THREAD

**Issue by g-klein** [a1studmuffin/SpaceshipGenerator#35]
I can't seem to get this to work using blender v2.83.0.  I am installing and it isn't showing any errors, but then I can't see Spaceship from the Add Mesh menu.  Not sure if I should downgrade blender to get this to work?

**Comment by ldo** [comment]
[This version](https://github.com/ldo/blender_spaceship_generator) is fully 2.8*x*-compatible.

**Comment by g-klein** [comment]
@ldo I am relatively new to blender so its entirely possibly I am just messing this up, but I cannot get the "Add -> Mesh -> Spaceship" to show up after trying install the plugin.

I am using blender v2.83.0 and add_mesh_SpaceshipGenerator-v1.6.0. 

**Additional info for you:**
The instructions say to use `File > User Preferences... > Add-ons > Install From File` but that menu doesn't exist in my Blender, so I am installing it by doing `Edit -> Preferences -> Add-ons -> Install` (which I am assuming is just the same menu but moved to a different place?)

To install, I am selecting `spaceship_generator.py` as the file.  

After installing, I get an info log in blender saying the module was installed.  
**However, if I search "space" in the installed modules nothing shows up.**

**Additional stuff I have tried**
I have tried installing it as an admin, installing latest version of python, restarting blender after installing the module, refreshing the module list.  I am using windows if that makes any kind of difference?  Nothing seems to work.

Any help would be greatly appreciated!  This tool looks amazing and I'd really like to get this working if possible!! Thank you so much for making such a cool looking tool :)

**Comment by ldo** [comment]
Do not unzip the `.zip` file. Simply select it directly for installation, and Blender will do the unzipping for you. Then it will show up in the Add menu as Add → Mesh → Spaceship.

**Comment by g-klein** [comment]
YES! IT WORKED!! Thank you so much!

**Comment by a1studmuffin** [comment]
Thanks all!
