### ISSUE TITLE
Error while enabling Addon (_init_.py line 18)

### ISSUE THREAD

**Issue by BurakTokak** [a1studmuffin/SpaceshipGenerator#4]
Thanks for the awesome script, but I have a problem while installing the addon.

Here is the screenshot of error dump.
![screenshot_1](https://cloud.githubusercontent.com/assets/5216601/16176187/f46f25a8-360f-11e6-916d-9a9a71460f57.png)

I'm not really experienced on Blender or python.

Using Blender v2.69

Thanks again.

**Comment by a1studmuffin** [comment]
Yeah I just tried now and the addon won't install/run below Blender 2.71, although the addon officially only supports 2.76 or greater. You'll need to update Blender to 2.71 or greater if you want to get it working. Thanks for checking it out :)
