### ISSUE TITLE
Cannot enable add-on

### ISSUE THREAD

**Issue by gossizappz** [a1studmuffin/SpaceshipGenerator#5]
Unable to enable add-on with following error:
![screenshot 2016-06-19 18 34 28](https://cloud.githubusercontent.com/assets/4251871/16176250/de533b50-364c-11e6-85e7-116619a1eb53.png)

Using version 2.77a

**Comment by a1studmuffin** [comment]
Wrong ZIP file :) You need to download the latest release ZIP in the Releases tab (https://github.com/a1studmuffin/SpaceshipGenerator/releases). Thanks for checking it out :)
