### ISSUE TITLE
[feature request] parameter GUI

### ISSUE THREAD

**Issue by Artanicus** [a1studmuffin/SpaceshipGenerator#6]
I have no idea how plugins work in Blender but it would be awesome if the paremeters and seed could be tweaked from a GUI. Some of the extreme examples look really awesome and the repeatability of a seed would be nice to surface as an option without editing the script.

**Comment by flarn2006** [comment]
Shouldn't this be closed now because of pull request #3?

**Comment by a1studmuffin** [comment]
Yep thanks. Once you've enabled the addon in Blender, you can select `Shift+A > Mesh > Spaceship` to create the spaceship, then under `Toolbar > Spaceship` (press `T` if the toolbar isn't visible) you can play with the parameters.
