### ISSUE TITLE
Can't enable installed addon

### ISSUE THREAD

**Issue by mishantrop** [a1studmuffin/SpaceshipGenerator#9]
Windows 7x64
Blender 2.77

How to reproduce:
1. Download https://github.com/a1studmuffin/SpaceshipGenerator/archive/master.zip
2. «Install from File...»
3. Enable addon

![277](https://cloud.githubusercontent.com/assets/5341208/16245103/f3a45072-3807-11e6-9fb8-8d057996b1d6.png)

**Comment by SGF-Git** [comment]
I have the same problem

**Comment by artistmatej** [comment]
Same here.

**Comment by willtheorangeguy** [comment]
Same here.

**Comment by taddmencer** [comment]
I have this same issue.

Running Blender 2.77a on a Windows 10 system

**Comment by a1studmuffin** [comment]
Wrong ZIP file. You need to download the latest release ZIP from the releases page. Here's the latest ZIP at the time of this comment:

https://github.com/a1studmuffin/SpaceshipGenerator/releases/download/v0.1.1/add_mesh_SpaceshipGenerator.zip

I'll update the instructions to be clearer. Cheers for the reports everyone.
